In [2]:
import torch
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [4]:
tensor = torch.tensor(arr, dtype=torch.int8)
tensor

tensor([1, 2, 3, 4], dtype=torch.int8)

In [5]:
x = torch.tensor(arr, dtype=torch.float16, requires_grad=True)
out = x.pow(2).sum()
out.backward()
x.grad

tensor([2., 4., 6., 8.], dtype=torch.float16)