In [1]:
import torch
import numpy as np

In [7]:
x = torch.arange(6).reshape((2, 3))
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [78]:
a = np.array([1, 2, 3, 4 ,5, 6])
a.reshape(2,3)
a

array([1, 2, 3, 4, 5, 6])

In [64]:
print(x)

tensor([[0, 1, 2],
        [3, 4, 5]])


In [63]:
x[:,1]

tensor([1, 4])

In [65]:
x[:,1:]

tensor([[1, 2],
        [4, 5]])

In [72]:
x.view(1,6)
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [81]:
import array
x = array.array('d',[1, 2, 3, 4])
x

array('d', [1.0, 2.0, 3.0, 4.0])