In [ ]:
import torch
import numpy as np

: 

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int32
<class 'numpy.ndarray'>


In [3]:
x = torch.from_numpy(arr)
# Equivalent to x = torch.as_tensor(arr)

print(x)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)


In [4]:
x = torch.tensor(arr, dtype=torch.int8)
x

tensor([1, 2, 3, 4, 5], dtype=torch.int8)